//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "globalSmtpSettings"
	/// <summary>Global - Smtp Settings</summary>
	public partial interface IGlobalSmtpSettings : IPublishedContent
	{
		/// <summary>Credential Password</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SmtpCredentialPassword { get; }

		/// <summary>Credential Username</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SmtpCredentialUsername { get; }

		/// <summary>Email From</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SmtpEmailFrom { get; }

		/// <summary>Enable Ssl</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		bool SmtpEnableSsl { get; }

		/// <summary>Host</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SmtpHost { get; }

		/// <summary>Port</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		int SmtpPort { get; }
	}

	/// <summary>Global - Smtp Settings</summary>
	[PublishedModel("globalSmtpSettings")]
	public partial class GlobalSmtpSettings : PublishedContentModel, IGlobalSmtpSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "globalSmtpSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalSmtpSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalSmtpSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Credential Password
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpCredentialPassword")]
		public virtual string SmtpCredentialPassword => GetSmtpCredentialPassword(this, _publishedValueFallback);

		/// <summary>Static getter for Credential Password</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSmtpCredentialPassword(IGlobalSmtpSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "smtpCredentialPassword");

		///<summary>
		/// Credential Username
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpCredentialUsername")]
		public virtual string SmtpCredentialUsername => GetSmtpCredentialUsername(this, _publishedValueFallback);

		/// <summary>Static getter for Credential Username</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSmtpCredentialUsername(IGlobalSmtpSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "smtpCredentialUsername");

		///<summary>
		/// Email From
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpEmailFrom")]
		public virtual string SmtpEmailFrom => GetSmtpEmailFrom(this, _publishedValueFallback);

		/// <summary>Static getter for Email From</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSmtpEmailFrom(IGlobalSmtpSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "smtpEmailFrom");

		///<summary>
		/// Enable Ssl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("smtpEnableSsl")]
		public virtual bool SmtpEnableSsl => GetSmtpEnableSsl(this, _publishedValueFallback);

		/// <summary>Static getter for Enable Ssl</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public static bool GetSmtpEnableSsl(IGlobalSmtpSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "smtpEnableSsl");

		///<summary>
		/// Host
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smtpHost")]
		public virtual string SmtpHost => GetSmtpHost(this, _publishedValueFallback);

		/// <summary>Static getter for Host</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSmtpHost(IGlobalSmtpSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "smtpHost");

		///<summary>
		/// Port
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("smtpPort")]
		public virtual int SmtpPort => GetSmtpPort(this, _publishedValueFallback);

		/// <summary>Static getter for Port</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public static int GetSmtpPort(IGlobalSmtpSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "smtpPort");
	}
}
