//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Page Error</summary>
	[PublishedModel("globalPageError")]
	public partial class GlobalPageError : PublishedContentModel, IGlobalPageHeadMetaSetting, IGlobalPageSitemapSetting
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "globalPageError";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalPageError, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalPageError(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Keywords: Type to add tags (press ENTER after each tag)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headKeywords")]
		public virtual global::System.Collections.Generic.IEnumerable<string> HeadKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadMetaSetting.GetHeadKeywords(this, _publishedValueFallback);

		///<summary>
		/// Social Share Image: The image used when someone shares the page on social media, such as, Twitter or Facebook. We suggest that you use an image of at least 1200x630 pixels.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headSocialShareImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeadSocialShareImage => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadMetaSetting.GetHeadSocialShareImage(this, _publishedValueFallback);

		///<summary>
		/// Title and Description: This is a preview of how your page may appear in search engines.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headTitleAndDescription")]
		public virtual global::SeoVisualizer.SeoValues HeadTitleAndDescription => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadMetaSetting.GetHeadTitleAndDescription(this, _publishedValueFallback);

		///<summary>
		/// Hidden Sitemap: This will add a 'noindex' meta tag to your page which stops it being indexed by search engines. This will also exclude this page from your sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapHiddenSitemap")]
		public virtual bool SitemapHiddenSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapHiddenSitemap(this, _publishedValueFallback);

		///<summary>
		/// Hidden their children: This will also exclude all page children from your sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapHiddenTheirChildren")]
		public virtual bool SitemapHiddenTheirChildren => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapHiddenTheirChildren(this, _publishedValueFallback);

		///<summary>
		/// Stop internal links being followed: This will add a 'nofollow' meta tag to your page which prevents search engine spiders from following links on this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapStopInternalLinksBeingFollowed")]
		public virtual bool SitemapStopInternalLinksBeingFollowed => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapStopInternalLinksBeingFollowed(this, _publishedValueFallback);

		///<summary>
		/// Sitemap XML change frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sitemapXmlChangeFrequency")]
		public virtual string SitemapXmlChangeFrequency => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapXmlChangeFrequency(this, _publishedValueFallback);

		///<summary>
		/// Sitemap XML Priority: Value between: 0-1 BUT IF THE VALUE IS A NUMBER {0 IT WILL AUTOMATICALLY NUMBER BY LEVEL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapXmlPriority")]
		public virtual decimal SitemapXmlPriority => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapXmlPriority(this, _publishedValueFallback);
	}
}
