//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "globalPageSitemapSetting"
	/// <summary>Global - Page Sitemap Setting</summary>
	public partial interface IGlobalPageSitemapSetting : IPublishedElement
	{
		/// <summary>Hidden Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		bool SitemapHiddenSitemap { get; }

		/// <summary>Hidden their children</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		bool SitemapHiddenTheirChildren { get; }

		/// <summary>Stop internal links being followed</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		bool SitemapStopInternalLinksBeingFollowed { get; }

		/// <summary>Sitemap XML change frequency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SitemapXmlChangeFrequency { get; }

		/// <summary>Sitemap XML Priority</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		decimal SitemapXmlPriority { get; }
	}

	/// <summary>Global - Page Sitemap Setting</summary>
	[PublishedModel("globalPageSitemapSetting")]
	public partial class GlobalPageSitemapSetting : PublishedElementModel, IGlobalPageSitemapSetting
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "globalPageSitemapSetting";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalPageSitemapSetting, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalPageSitemapSetting(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Hidden Sitemap: This will add a 'noindex' meta tag to your page which stops it being indexed by search engines. This will also exclude this page from your sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapHiddenSitemap")]
		public virtual bool SitemapHiddenSitemap => GetSitemapHiddenSitemap(this, _publishedValueFallback);

		/// <summary>Static getter for Hidden Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public static bool GetSitemapHiddenSitemap(IGlobalPageSitemapSetting that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "sitemapHiddenSitemap");

		///<summary>
		/// Hidden their children: This will also exclude all page children from your sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapHiddenTheirChildren")]
		public virtual bool SitemapHiddenTheirChildren => GetSitemapHiddenTheirChildren(this, _publishedValueFallback);

		/// <summary>Static getter for Hidden their children</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public static bool GetSitemapHiddenTheirChildren(IGlobalPageSitemapSetting that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "sitemapHiddenTheirChildren");

		///<summary>
		/// Stop internal links being followed: This will add a 'nofollow' meta tag to your page which prevents search engine spiders from following links on this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapStopInternalLinksBeingFollowed")]
		public virtual bool SitemapStopInternalLinksBeingFollowed => GetSitemapStopInternalLinksBeingFollowed(this, _publishedValueFallback);

		/// <summary>Static getter for Stop internal links being followed</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public static bool GetSitemapStopInternalLinksBeingFollowed(IGlobalPageSitemapSetting that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "sitemapStopInternalLinksBeingFollowed");

		///<summary>
		/// Sitemap XML change frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sitemapXmlChangeFrequency")]
		public virtual string SitemapXmlChangeFrequency => GetSitemapXmlChangeFrequency(this, _publishedValueFallback);

		/// <summary>Static getter for Sitemap XML change frequency</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSitemapXmlChangeFrequency(IGlobalPageSitemapSetting that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "sitemapXmlChangeFrequency");

		///<summary>
		/// Sitemap XML Priority: Value between: 0-1 BUT IF THE VALUE IS A NUMBER {0 IT WILL AUTOMATICALLY NUMBER BY LEVEL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapXmlPriority")]
		public virtual decimal SitemapXmlPriority => GetSitemapXmlPriority(this, _publishedValueFallback);

		/// <summary>Static getter for Sitemap XML Priority</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public static decimal GetSitemapXmlPriority(IGlobalPageSitemapSetting that, IPublishedValueFallback publishedValueFallback) => that.Value<decimal>(publishedValueFallback, "sitemapXmlPriority");
	}
}
