//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Global - Responsive Image Settings</summary>
	[PublishedModel("globalResponsiveImageSettings")]
	public partial class GlobalResponsiveImageSettings : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "globalResponsiveImageSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GlobalResponsiveImageSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GlobalResponsiveImageSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Extend Sizes SrcSet: Additional dimensions used for the img tag's srcset data If not entered, default will only take 3 sizes for srcset
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("repImgExtendSizesSrcSet")]
		public virtual global::System.Collections.Generic.IEnumerable<string> RepImgExtendSizesSrcSet => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "repImgExtendSizesSrcSet");

		///<summary>
		/// Max Width Desktop (px): Default: 1920px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("repImgMaxWidthDesktop")]
		public virtual int RepImgMaxWidthDesktop => this.Value<int>(_publishedValueFallback, "repImgMaxWidthDesktop");

		///<summary>
		/// Max Width Mobile (px): Default: 768px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("repImgMaxWidthMobile")]
		public virtual int RepImgMaxWidthMobile => this.Value<int>(_publishedValueFallback, "repImgMaxWidthMobile");

		///<summary>
		/// Max Width Table (px): Default: 1024px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("repImgMaxWidthTable")]
		public virtual int RepImgMaxWidthTable => this.Value<int>(_publishedValueFallback, "repImgMaxWidthTable");

		///<summary>
		/// Turn Off Responsive Image: Turn on: Image url links will be resized and converted to .webp format.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("repImgTurnOffResponsiveImage")]
		public virtual bool RepImgTurnOffResponsiveImage => this.Value<bool>(_publishedValueFallback, "repImgTurnOffResponsiveImage");
	}
}
