//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v16.0.0+9812630
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Page Home</summary>
	[PublishedModel("uTPro__PageHome")]
	public partial class UTpro__PageHome : PublishedContentModel, IGlobalPageHeadMetaSetting, IGlobalPageHeadSocialMetaSetting, IGlobalPageNavigationConfigSettingForHomePage, IGlobalPageNavigationSetting, IGlobalPageScriptSetting, IGlobalPageSitemapSetting
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const string ModelTypeAlias = "uTPro__PageHome";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<UTpro__PageHome, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public UTpro__PageHome(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Keywords: Type to add tags (press ENTER after each tag)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headKeywords")]
		public virtual global::System.Collections.Generic.IEnumerable<string> HeadKeywords => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadMetaSetting.GetHeadKeywords(this, _publishedValueFallback);

		///<summary>
		/// Social Share Image: The image used when someone shares the page on social media, such as, Twitter or Facebook. We suggest that you use an image of at least 1200x630 pixels.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headSocialShareImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeadSocialShareImage => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadMetaSetting.GetHeadSocialShareImage(this, _publishedValueFallback);

		///<summary>
		/// Title and Description: This is a preview of how your page may appear in search engines.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headTitleAndDescription")]
		public virtual global::SeoVisualizer.SeoValues HeadTitleAndDescription => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadMetaSetting.GetHeadTitleAndDescription(this, _publishedValueFallback);

		///<summary>
		/// Facebook App ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("facebookAppId")]
		public virtual string FacebookAppId => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetFacebookAppId(this, _publishedValueFallback);

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogDescription")]
		public virtual string OgDescription => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetOgDescription(this, _publishedValueFallback);

		///<summary>
		/// Image: The URL of the image that appears when someone shares the content to Facebook.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OgImage => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetOgImage(this, _publishedValueFallback);

		///<summary>
		/// Title: The title of your article without any branding such as your site name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogTitle")]
		public virtual string OgTitle => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetOgTitle(this, _publishedValueFallback);

		///<summary>
		/// Type: The type of media of your content. This tag impacts how your content shows up in News Feed. If you don't specify a type,the default is website. Each URL should be a single object, so multiple og:type values are not possible.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ogType")]
		public virtual string OgType => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetOgType(this, _publishedValueFallback);

		///<summary>
		/// Card Type: Select the twitter card type you need to use.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterCardType")]
		public virtual string TwitterCardType => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetTwitterCardType(this, _publishedValueFallback);

		///<summary>
		/// Description: A description that concisely summarizes the content as appropriate for presentation within a Tweet. You should not re-use the title as the description or use this field to describe the general services provided by the website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterDescription")]
		public virtual string TwitterDescription => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetTwitterDescription(this, _publishedValueFallback);

		///<summary>
		/// Image: A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TwitterImage => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetTwitterImage(this, _publishedValueFallback);

		///<summary>
		/// Image Alt: A text description of the image conveying the essential nature of an image to users who are visually impaired. Maximum 420 characters.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterImageAlt")]
		public virtual string TwitterImageAlt => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetTwitterImageAlt(this, _publishedValueFallback);

		///<summary>
		/// Site: The Twitter @username the card should be attributed to.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterSite")]
		public virtual string TwitterSite => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetTwitterSite(this, _publishedValueFallback);

		///<summary>
		/// Title: A concise title for the related content.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterTitle")]
		public virtual string TwitterTitle => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageHeadSocialMetaSetting.GetTwitterTitle(this, _publishedValueFallback);

		///<summary>
		/// Page Not Found
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageNotFound")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent PageNotFound => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageNavigationConfigSettingForHomePage.GetPageNotFound(this, _publishedValueFallback);

		///<summary>
		/// Content Redirect: Use when you want to serve content from another node without affecting the visible URL.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoInternalRedirectId => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageNavigationSetting.GetUmbracoInternalRedirectId(this, _publishedValueFallback);

		///<summary>
		/// Url Redirect: Use when you want users and search engines to be redirected to a different URL (302 temporary redirect).  
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoRedirect")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent UmbracoRedirect => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageNavigationSetting.GetUmbracoRedirect(this, _publishedValueFallback);

		///<summary>
		/// Alternative URL: Use this field to provide multiple URLs for your page. Please note that the values you use must be lowercase, not use a leading slash and not use a file extension.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageNavigationSetting.GetUmbracoUrlAlias(this, _publishedValueFallback);

		///<summary>
		/// Alternative name: Use this field to set an alternative name for your page. This will override the default node name that is used as the URL of this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlName")]
		public virtual string UmbracoUrlName => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageNavigationSetting.GetUmbracoUrlName(this, _publishedValueFallback);

		///<summary>
		/// Body closing scripts: Anything you enter here will be placed before the closing {/body} tag on this page of your website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bodyClosingScripts")]
		public virtual string BodyClosingScripts => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageScriptSetting.GetBodyClosingScripts(this, _publishedValueFallback);

		///<summary>
		/// Body opening scripts: Anything you enter here will be placed after the opening {body} tag on this page of your website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bodyOpeningScripts")]
		public virtual string BodyOpeningScripts => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageScriptSetting.GetBodyOpeningScripts(this, _publishedValueFallback);

		///<summary>
		/// Header closing scripts: Anything you enter here will be placed before the closing {/head} tag on this page of your website. 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerClosingScripts")]
		public virtual string HeaderClosingScripts => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageScriptSetting.GetHeaderClosingScripts(this, _publishedValueFallback);

		///<summary>
		/// Header opening scripts: Anything you enter here will be placed after the opening {head} tag on this page of your website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerOpeningScripts")]
		public virtual string HeaderOpeningScripts => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageScriptSetting.GetHeaderOpeningScripts(this, _publishedValueFallback);

		///<summary>
		/// Hidden Sitemap: This will add a 'noindex' meta tag to your page which stops it being indexed by search engines. This will also exclude this page from your sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapHiddenSitemap")]
		public virtual bool SitemapHiddenSitemap => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapHiddenSitemap(this, _publishedValueFallback);

		///<summary>
		/// Hidden their children: This will also exclude all page children from your sitemap.xml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapHiddenTheirChildren")]
		public virtual bool SitemapHiddenTheirChildren => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapHiddenTheirChildren(this, _publishedValueFallback);

		///<summary>
		/// Stop internal links being followed: This will add a 'nofollow' meta tag to your page which prevents search engine spiders from following links on this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapStopInternalLinksBeingFollowed")]
		public virtual bool SitemapStopInternalLinksBeingFollowed => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapStopInternalLinksBeingFollowed(this, _publishedValueFallback);

		///<summary>
		/// Sitemap XML change frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sitemapXmlChangeFrequency")]
		public virtual string SitemapXmlChangeFrequency => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapXmlChangeFrequency(this, _publishedValueFallback);

		///<summary>
		/// Sitemap XML Priority: Value between: 0-1 BUT IF THE VALUE IS A NUMBER {0 IT WILL AUTOMATICALLY NUMBER BY LEVEL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "16.0.0+9812630")]
		[ImplementPropertyType("sitemapXmlPriority")]
		public virtual decimal SitemapXmlPriority => global::Umbraco.Cms.Web.Common.PublishedModels.GlobalPageSitemapSetting.GetSitemapXmlPriority(this, _publishedValueFallback);
	}
}
